stuff
Nycz-lab/BallE pull request #7
Opened 2022-08-08 15:03 UTC by DevKevMo

2022-08-08 18:39 UTC, Nycz-lab requested changes

2022-08-08 18:39 UTC, Nycz-lab commented on main.py
> +        soundIndex = random.randint(0, len(balle.soundNames))
`len(balle.soundNames) -1 `
otherwise out of index

2022-08-09 06:41 UTC, 71982 approved these changes
gj

2022-08-09 06:41 UTC, Nycz-lab approved these changes

2022-08-09 06:41 UTC, 71982 approved these changes

2022-08-09 06:42 UTC, merged